### ISSUE TITLE
Issue Commenting

### ISSUE THREAD

**Issue by gquemener** [Behat/GithubExtension#1] opened 2012-08-09 13:57 UTC
So to quickly explain what is **Issue Commenting**,
It's a mechanism that will automaticly post a comment on the issue containing the behat feature.
This comment will contains informations like the date of the run and the result of each scenarios.
Example: https://github.com/gquemener/dotfiles/issues/1

This feature can quickly become a pain (due to the number of comment it generates).
So 2 solutions (at least) here:
- We provide a command option to enable it (and we disable it by default) like `--comment-issue`
- We edit the issue and add a result section at the end (and we can also provide an option to enable this, in order to limit calls to github api calls), but we won't have access to the history.

In the other hand, who cares about knowing that features were passing or failing at a given date?
Isn't what really matter the last known state of the feature?

Another possibility would be to remove all generated comments before posting a new one, but it's very similar to edit the issue itself.

The big advantage of editing the issue is to directly see the result of the feature execution under the feature.

So, feel free to share your user experience opinion here.

**Comment by stof** [comment] 2012-08-09 14:12
The issue when editing the issue is that it will invalidate the feature cache. So maybe it should be done only when the state changes ?
And I think it should be able to disable it (either through an option or through the behat.yml file) as you may not want to send comments about failures each time you are trying something locally; Thus, commenting saying the feature is broken because you broke it locally in your dev branch looks wrong. Comments look like a feature which should be enabled only for the CI server.

**Comment by clemherreman** [comment] 2012-08-09 14:15
IMO what's important is to know if the feature is broken or green. I vote for editing the result to reflect the state of the feature after the last run.

As @stof said, it's vital to be able to disable it, I'd say that's should even be the default value, as tests ran locally while developing are failing quite often, and as the state displayed should be more like a "CI-like" status, not reflecting the last syntax error a developer made.

**Comment by gquemener** [comment] 2012-08-09 14:16
> Comments look like a feature which should be enabled only for the CI server.

Yep, I'm +1 with that.

And you're right about this cache invalidation problem @stof.

mmh...

**Comment by gquemener** [comment] 2012-08-09 14:24
So the question is: keeping or not history of feature executions in comments?

**Comment by clemherreman** [comment] 2012-08-09 18:20
History is useless, having the  status is useful as dashboard. If you need
history then you need a real CI, not a GitHub issue :)

Le 9 août 2012 à 16:24, "Gildas Quéméner" notifications@github.com a
écrit :

So the question is: keeping or not history of feature executions in
comments?

—
Reply to this email directly or view it on
GitHubhttps://github.com/Behat/GithubExtension/issues/1#issuecomment-7615301.

**Comment by everzet** [comment] 2012-08-09 19:39
Comments should be created **only** in CI environment and **only** for staging/testing branch. This is the only way you'd be able to see when feature is broken or implemented naturally. I break my features 5 times a day in my own feature branches, but what's important is their state in staging branch, tested in controlled environment (CI server).

So yes, it should be either CLI or `behat.yml` option, disabled by default. And this way, i see no problems in creating new comment for each feature state change as it's important information. And it preserves history. And history is important, @clemherreman, if you want to optimize processes/flow in next iterations ;)

It's just my opinion based on my experience and plans :)

**Comment by joshribakoff** [comment] 2013-06-29 11:41
I agree with everzet here, this behavior should happen only when some flag or behat.yml setting is passed. Additionally, it should work like a CI server. Comment when:

The commit results in a failed test run ("this commit broke the build", & "build still broken")
The commit fixes a broken build ("this commit fixed it")

Do not comment when the last status was passing and this commit leaves it still passing. Also when a commit makes it fail it should open the issue, and when a commit makes it pass it should close the issue. It should never rewrite history. If that test fails every other week, then you'll just have a comment every other week.

**Closed as completed** 2015-07-20 17:37 UTC
